
export const Assets = {
    // Icons
    ICON_ARM_ACTION: "img/ArmActionIcon.svg",
    ICON_LEG_ACTION: "img/LegActionIcon.svg",
    ICON_SPECIAL_ACTION: "img/SpecialActionIcon.svg",
    ICON_PARRY_BOTH: "img/ParryIcon_Both.svg",
    ICON_PARRY_HIGH: "img/ParryIcon_High.svg",
    ICON_PARRY_LOW: "img/ParryIcon_Low.svg",
    ICON_PARRY_NONE: "img/ParryIcon_None.svg",
    ICON_PARRY_SMALL: "img/ParryIcon_Small.svg",
    ICON_RANGE: "img/RangeIcon.svg",
    ICON_INSTANT_INVERTED: "img/InstantIconInverted.svg",
    ICON_CHAMBER: "img/ChamberIcon.svg",
    ICON_COUNTER: "img/CounterIcon.svg",
    ICON_TOKEN: "img/TokenIcon.svg",
    ICON_DOMINATE: "img/DominateIcon.svg",
    ICON_FLOW: "img/FlowIcon.svg",
    ICON_CELERITY: "img/CelerityIcon.svg",
    ICON_AUDACITY: "img/AudacityIcon.svg",
    ICON_INSIGHT: "img/InsightIcon.svg",
    ICON_FORTITUDE: "img/FortitudeIcon.svg",
    // TODO: Talent, Footwork
    // Tiers
    TIER_0_ACTION: "img/Tier_0_Action.svg",
    TIER_1_ACTION: "img/Tier_1_Action.svg",
    TIER_2_ACTION: "img/Tier_2_Action.svg",
    TIER_3_ACTION: "img/Tier_3_Action.svg",
    TIER_0_TALENT: "img/Tier_0_Talent.svg",
    TIER_1_TALENT: "img/Tier_1_Talent.svg",
    TIER_2_TALENT: "img/Tier_2_Talent.svg",
    TIER_3_TALENT: "img/Tier_3_Talent.svg",
    // Arches and Decor
    ARCH_LEFT: "img/Arch_Left.svg",
    ARCH_RIGHT: "img/Arch_Right.svg",
    TITLE_TALENT: "img/Title_Talent.svg",
    TITLE_TRAINING: "img/Title_Talent.svg", // Same for now
    // Frames
    // Base
    BASE_ACTION_DEFAULT: "img/Base_Action_Default.svg",
    BASE_ACTION_AUDACITY: "img/Base_Action_Audacity.svg",
    BASE_ACTION_CELERITY: "img/Base_Action_Celerity.svg",
    BASE_ACTION_FORTITUDE: "img/Base_Action_Fortitude.svg",
    BASE_ACTION_INSIGHT: "img/Base_Action_Insight.svg",
    BASE_ACTION_FOOTWORK: "img/Base_Action_Footwork.svg",
    BASE_ACTION_TOKEN: "img/Base_Action_Token.svg",
    BASE_TALENT_DEFAULT: "img/Base_Talent_Default.svg",
    BASE_TRAINING_DEFAULT: "img/Base_Training_Default.svg",
    BASE_TRAINING_AUDACITY: "img/Base_Training_Audacity.svg",
    BASE_TRAINING_CELERITY: "img/Base_Training_Celerity.svg",
    BASE_TRAINING_FORTITUDE: "img/Base_Training_Fortitude.svg",
    BASE_TRAINING_INSIGHT: "img/Base_Training_Insight.svg",
    BASE_TRAINING_FOOTWORK: "img/Base_Training_Footwork.svg",
    BASE_TRAINING_MIXED: "img/Base_Training_Mixed.svg",
};
